CREATE TABLE Tasks (
  ID INTEGER PRIMARY KEY NOT NULL,
  UUID TEXT NOT NULL,
  Content TEXT NOT NULL,
  Priority INTEGER NOT NULL DEFAULT 0,
  TagUUIDs TEXT,
  IsComplete BOOLEAN NOT NULL DEFAULT 0,
  CreationInformationUUID TEXT NOT NULL
)