pub const ERROR_DETAILS_KEY: &str = "error_details";
pub const INTERNAL_ERROR: &str = "Internal error";
pub const USER_NOT_CREATED_ERROR_MESSAGE: &str = "User not created";
pub const CREATION_INFORMATION_NOT_CREATED_ERROR_MESSAGE: &str = "Creation information not created";
pub const CREATION_INFORMATION_NOT_UPDATED_ERROR_MESSAGE: &str = "Creation information not updated";
pub const LIST_NOT_CREATED_ERROR_MESSAGE: &str = "List not created";
pub const LIST_NOT_UPDATED_ERROR_MESSAGE: &str = "List not updated";
pub const TASK_NOT_CREATED_ERROR_MESSAGE: &str = "Task not created";
pub const TASK_NOT_ADDED_ERROR_MESSAGE: &str = "Task not added";
